name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Only deploy on main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Install dependencies
        run: npm install --production

      - name: Run database migrations
        run: node database/migrations/runMigrations.js

      - name: Seed the database
        run: |
          node seeds/seedUsers.js
          node seeds/seedAppointments.js
          node seeds/seedMedicalRecords.js

      - name: Deploy to server
        env:
          NODE_ENV: production
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # Use GitHub Secrets for sensitive data
        run: |
          ssh user@your-server-ip "cd /path/to/your/app && git pull origin main && npm install --production && pm2 restart salma-unity-care-hospital"

      - name: Notify deployment
        run: echo "Deployment completed successfully!"
